version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip" # uv supports pip ecosystem
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      linting:
        patterns:
          - "ruff"
          - "vulture"
          - "pyright"
